### ISSUE TITLE
脚本里的time_zone写错了

### ISSUE THREAD

**Issue by littleheary** [X-Mars/Quick-Installation-ZABBIX#3]
脚本里是RPC,应该是PRC
不然报错。

**Comment by 448348040** [comment]
Password is  incorrect

**Comment by 666sit** [comment]
感谢littleheary，你是对的！把RPC改成PRC就可以用了，如果知道原因的话麻烦解释一下，非常感谢！！👍

**Comment by smxzi** [comment]
> 脚本里是RPC,应该是PRC
> 不然报错。

感谢littleheary，你是对的！把RPC改成PRC就可以用了，如果知道原因的话麻烦解释一下，非常感谢！！👍

**Comment by smxzi** [comment]
> Password is incorrect

用户名是admin
密码是zabbix

**Comment by X-Mars** [comment]
已修改
