### ISSUE TITLE
系统是rocky linux 8.7无法使用zabbix6.0一键安装脚本

### ISSUE THREAD

**Issue by Hi-360** [X-Mars/Quick-Installation-ZABBIX#4]
![image](https://github.com/X-Mars/Quick-Installation-ZABBIX/assets/99636954/ab280dba-7dc3-4a8d-9ab1-dfa8ee12882d)
你好 我使用的是rocky linux8.7  无法使用你提供的zabbix6.0一键安装脚本

**Comment by X-Mars** [comment]
直接clone，或者用vscode编辑。

**Comment by X-Mars** [comment]
编码错误
